AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vanity-number-converter

  Sample SAM Template for vanity-number-converter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Resources:
  VanityNumberFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello_world.app.lambda_handler
      Runtime: python3.8
      CodeUri: hello_world/
      Environment:
        Variables:
          TABLE_NAME: VanityNumbers
      Policies:
        - AmazonDynamoDBFullAccess

  VanityNumberTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: VanityNumbers
      AttributeDefinitions:
        - AttributeName: PhoneNumber
          AttributeType: S
      KeySchema:
        - AttributeName: PhoneNumber
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5